server:
  tomcat:
    uri-encoding: UTF-8
  port: 8088
spring:
  profiles:
    active: dev
  application:
    name: ware-test-junit
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

# mybatis 配置
mybatis:
  type-aliases-package: com.junit.tool.entity.*
  mapper-locations: classpath:/mapper/*.xml