server:
  tomcat:
    uri-encoding: UTF-8
  port: 7022
spring:
  profiles:
    active: dev
  application:
    name: ware22-page-statics
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
