server:
  tomcat:
    uri-encoding: UTF-8
  port: 18001
spring:
  profiles:
    active: dev
  application:
    name: nacos-spring-boot-demo
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true