nacos:
  config:
    server-addr: @nacos.ipport@
    namespace: @nacos.namespace@ #prod
    group: platform_group
    data-ids: z-a
    type: yaml
    auto-refresh: true
    bootstrap:
      enable: true
  discovery:
    server-addr: @nacos.ipport@
    namespace: @nacos.namespace@ #prod
    auto-register: true #自动注册
    register:
      service-name: nacos-reg #这里优先级高于spring.application.name
      group: platform
#    group: DEFAULT_GROUP