server:
  port: 8401
spring:
  application:
    name: sentinel-spring-cloud-nacos-demo
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719  #默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.56.101:8848
            dataId: sentinel-spring-cloud-nacos-demo
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: '*'