server:
  port: 10001
  #servlet:
    #context-path: /dubbo-consumer

dubbo:
  application:
    name: dubbo-consumer
  registry:
    #address: nacos://127.0.0.1:8848
    address: nacos://@nacos.ipport@
    #address: zookeeper://127.0.0.1:2181
