spring:
  cloud:
    nacos:

      discovery:
        server-addr: 192.168.56.102:8848
        namespace: prod
        group: NACOS_GROUP_DISCOVERY
        username: nacos
        password: Tt_12345

server:
  port: 50001
dubbo:
  cloud:
    subscribed-services: "*"
  scan:
    base-packages: com.demo.nacos.nscdp.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost



