server:
  tomcat:
    uri-encoding: UTF-8
  port: 8088
spring:
  profiles:
    active: dev
  application:
    name: ware-param-check
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true