server:
  port: 50000 #服务端口

spring:
  application:
    name: springcloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:8848 #nacos服务地址
        namespace: prod
        group: NACOS_GROUP_DISCOVERY
    gateway:
      discovery:
        locator:
          enabled: true #使用服务发现路由
      routes:
        - id: SERVICE-ONE #设置路由id(理论上是可以随便写的)
          uri: lb://cx #设置路由的url lb://nacos服务注册名称
          predicates:
            - Path=/gcx/** #路径匹配规则
          filters:
            - StripPrefix=1