spring:
  application:
    name: cx
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.102:8848
        namespace: prod
        group: NACOS_GROUP_DISCOVERY
        username: nacos
        password: Tt_12345

server:
  port: 50002
dubbo:
  cloud:
    subscribed-services: "*"
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost

